import type { Metadata } from "next";

import "./globals.css";
import StoreProvider from "./StoreProvider";
import styles from './styles.module.css'
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  canvas
}: Readonly<{
  children: React.ReactNode;
  canvas: React.ReactNode;
  menuBar: React.ReactNode;
  propertyBar: React.ReactNode;
  statusBar: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <div className={styles.overlay}>
            {children}
          </div>
          <canvas>

          </canvas>
        </body>
      </html>
    </StoreProvider>
  );
}
